name: "ShellCheck"

on:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'refs/pull/*'
    tags:

jobs:
  shellcheck:
    name: "ShellCheck"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4

      - name: "Run ShellCheck"
        uses: "reviewdog/action-shellcheck@v1"
        with:
          fail_on_error: true
